Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace la_tienda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class storeEntities : DbContext
    {
        public storeEntities()
            : base("name=storeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<productos> productos { get; set; }
    }
}

Models/Model1.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\Users\manue\OneDrive\Escritorio\Proyect_Orte\C#\la tienda\Models\Model1.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Models/productos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace la_tienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_producto { get; set; }
        public string nombre_producto { get; set; }
        public int cantidad_producto { get; set; }
        public int valor_producto { get; set; }
        public string foto_producto { get; set; }
        public string descripcion_prducto { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace la_tienda.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/productosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using la_tienda.Models;

namespace la_tienda.Controllers
{
    public class productosController : Controller
    {
        private storeEntities db = new storeEntities();

        // GET: productos
        public ActionResult Index()
        {
            return View(db.productos.ToList());
        }

        // GET: productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // GET: productos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_producto,nombre_producto,cantidad_producto,valor_producto,foto_producto,descripcion_prducto")] productos productos)
        {
            if (ModelState.IsValid)
            {
                db.productos.Add(productos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productos);
        }

        // GET: productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_producto,nombre_producto,cantidad_producto,valor_producto,foto_producto,descripcion_prducto")] productos productos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(productos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productos);
        }

        // GET: productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            productos productos = db.productos.Find(id);
            if (productos == null)
            {
                return HttpNotFound();
            }
            return View(productos);
        }

        // POST: productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            productos productos = db.productos.Find(id);
            db.productos.Remove(productos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Supermarket</h1>
    <p class="lead">Productos Frescos a Toda Hora..</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>@Html.ActionLink("Productos","Index","productos")</h2>
        <p>
           Registra tus Productos Aqui!
        </p>
    </div>
    <div class="col-md-4">
        <img src="https://cdn.pixabay.com/photo/2019/10/05/08/53/shop-4527402__340.jpg"alt="foto1" class="img"/>
        <p>En nuestro supermercado ofresemos pos mejores prodcutos de la canasta familiar</p>
    </div>
    <div class="col-md-4">
        <img src="https://cdn.pixabay.com/photo/2019/10/04/08/28/escalator-4525063__340.jpg" alt="foto2" class="img"/>
        <p>las ofrertas para nuestros clientes son la mejores del mercados</p>
    </div>
</div>

<style>

    .jumbotron {
        background-image: url("https://media.istockphoto.com/photos/healthy-fresh-rainbow-colored-fruits-and-vegetables-in-a-row-picture-id1208790364?k=20&m=1208790364&s=612x612&w=0&h=EMmRWT5P5qbUvy95RxDtUSWrttlIsuXqjzRFhnTxqMQ= ");
        background-size: cover;
        color:#ffffff;
    }
    .img {
        width:300px;
        height:200px
    }
    p {
        font-family:Arial, Helvetica, sans-serif;
        font-size:16px;
        font-weight:100;
    }


</style>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Supermarket</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="body">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Supermarket", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ofertas del dia", "Index", "Home")</li>
                    <li>@Html.ActionLink("Servicios", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="footer">
            <p>&copy; @DateTime.Now.Year - Aplicación Desarrollada por Carlos Ortega ASP.NET </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <style>

        .body {
            background: #00b09b; /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #96c93d, #00b09b); /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #96c93d, #00b09b); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }


    </style>


</body>
</html>

Views/productos/Create.cshtml
@model la_tienda.Models.productos

@{
    ViewBag.Title = "Crear Producto";
}

<h2>Crear Producto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valor_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion_prducto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion_prducto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion_prducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/productos/Delete.cshtml
@model la_tienda.Models.productos

@{
    ViewBag.Title = "Borrar Producto";
}

<h2>Borrar Producto</h2>

<h3>¿Estás seguro de que quieres eliminar esto?</h3>
<div>
    <h4>productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantidad_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidad_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.valor_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valor_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion_prducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion_prducto)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" id="btn" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>
<style>
    #btn{
        background-color: #f60a0a;
    }
</style>

Views/productos/Details.cshtml
@model la_tienda.Models.productos

@{
    ViewBag.Title = "Detalle del Producto";
}

<h2>Detalle de Producto</h2>

<div>
    <h4>productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cantidad_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cantidad_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.valor_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valor_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.foto_producto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.foto_producto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion_prducto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion_prducto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar Producto", "Edit", new { id = Model.id_producto }) |
    @Html.ActionLink("Regresar a la lista", "Index")
</p>

Views/productos/Edit.cshtml
@model la_tienda.Models.productos

@{
    ViewBag.Title = "Editar Producto";
}

<h2>Editar Producto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_producto)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.valor_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto_producto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.foto_producto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.foto_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion_prducto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion_prducto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion_prducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/productos/Index.cshtml
@model IEnumerable<la_tienda.Models.productos>

@{
    ViewBag.Title = "Listado de Productos";
}

<h2>Lista de Productos</h2>

<p>
    @Html.ActionLink("Crear Producto ", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nombre_producto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad_producto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.valor_producto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.foto_producto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion_prducto)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre_producto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cantidad_producto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.valor_producto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.foto_producto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.descripcion_prducto)
        </td>
        <td>
            <button class="boton1">@Html.ActionLink("Edit", "Edit", new { id = item.id_producto })</button>
            <button class="boton2">@Html.ActionLink("Details", "Details", new { id = item.id_producto })</button>
            <button class="boton3">
                @Html.ActionLink("Delete", "Delete", new { id = item.id_producto })
            </button>
            
            
        </td>
    </tr>
}

</table>
<style>
    .boton1 {
        background-color:#62dcf2;
        border-radius:4px;
    }
    .boton2 {
        background-color: #00ffff;
        border-radius: 4px;
    }
    .boton3 {
        background-color: #f60a0a;
        border-radius: 4px;
    }
</style>